<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions3.proto

namespace GPBMetadata;

class Suggestions3
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a80020a1273756767657374696f6e73332e70726f746f22580a0c736561" .
            "7263685f6d6f64656c12120a0a73756767657374696f6e18012001280912" .
            "100a08756e6b6e6f776e3118022001280512100a08756e6b6e6f776e3218" .
            "052001280912100a08756e6b6e6f776e3318062001280922180a0a756e6b" .
            "6e6f776e5f6964120a0a026964180d20012809226e0a1473756767657374" .
            "696f6e735f726573706f6e736512170a0f7265717565737465645f717565" .
            "727918012001280912230a0c7365617263685f6d6f64656c18022003280b" .
            "320d2e7365617263685f6d6f64656c12180a035f696418032001280b320b" .
            "2e756e6b6e6f776e5f6964620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

