<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions3.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>search_model</code>
 */
class search_model extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string suggestion = 1;</code>
     */
    private $suggestion = '';
    /**
     * Generated from protobuf field <code>int32 unknown1 = 2;</code>
     */
    private $unknown1 = 0;
    /**
     * Generated from protobuf field <code>string unknown2 = 5;</code>
     */
    private $unknown2 = '';
    /**
     * Generated from protobuf field <code>string unknown3 = 6;</code>
     */
    private $unknown3 = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $suggestion
     *     @type int $unknown1
     *     @type string $unknown2
     *     @type string $unknown3
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Suggestions3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string suggestion = 1;</code>
     * @return string
     */
    public function getSuggestion()
    {
        return $this->suggestion;
    }

    /**
     * Generated from protobuf field <code>string suggestion = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSuggestion($var)
    {
        GPBUtil::checkString($var, True);
        $this->suggestion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 unknown1 = 2;</code>
     * @return int
     */
    public function getUnknown1()
    {
        return $this->unknown1;
    }

    /**
     * Generated from protobuf field <code>int32 unknown1 = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUnknown1($var)
    {
        GPBUtil::checkInt32($var);
        $this->unknown1 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unknown2 = 5;</code>
     * @return string
     */
    public function getUnknown2()
    {
        return $this->unknown2;
    }

    /**
     * Generated from protobuf field <code>string unknown2 = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUnknown2($var)
    {
        GPBUtil::checkString($var, True);
        $this->unknown2 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unknown3 = 6;</code>
     * @return string
     */
    public function getUnknown3()
    {
        return $this->unknown3;
    }

    /**
     * Generated from protobuf field <code>string unknown3 = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUnknown3($var)
    {
        GPBUtil::checkString($var, True);
        $this->unknown3 = $var;

        return $this;
    }

}

