<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions3.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>suggestions_response</code>
 */
class suggestions_response extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string requested_query = 1;</code>
     */
    private $requested_query = '';
    /**
     * Generated from protobuf field <code>repeated .search_model search_model = 2;</code>
     */
    private $search_model;
    /**
     * Generated from protobuf field <code>.unknown_id _id = 3;</code>
     */
    private $_id = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $requested_query
     *     @type \search_model[]|\Google\Protobuf\Internal\RepeatedField $search_model
     *     @type \unknown_id $_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Suggestions3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string requested_query = 1;</code>
     * @return string
     */
    public function getRequestedQuery()
    {
        return $this->requested_query;
    }

    /**
     * Generated from protobuf field <code>string requested_query = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestedQuery($var)
    {
        GPBUtil::checkString($var, True);
        $this->requested_query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .search_model search_model = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField|search_model[]
     */
    public function getSearchModel()
    {
        return $this->search_model;
    }

    /**
     * Generated from protobuf field <code>repeated .search_model search_model = 2;</code>
     * @param \search_model[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSearchModel($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \search_model::class);
        $this->search_model = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.unknown_id _id = 3;</code>
     * @return \unknown_id
     */
    public function getId()
    {
        return $this->_id;
    }

    /**
     * Generated from protobuf field <code>.unknown_id _id = 3;</code>
     * @param \unknown_id $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \unknown_id::class);
        $this->_id = $var;

        return $this;
    }

}

